name: Build App for Android & iOS
description: Build Capacitor app for Android and iOS platforms

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build the web assets
      - name: Build web assets
        run: export MODE=prod && npm run build

      # Install Capacitor CLI
      - name: Install Capacitor CLI
        run: npm install -g @capacitor/cli

      # Setup Java for Android
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Setup Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # Sync and build Android
      - name: Sync and build Android
        run: |
          npx cap sync android
          cd android
          ./gradlew assembleDebug
        env:
          ANDROID_SDK_ROOT: ${{ env.ANDROID_HOME }}

      # Setup Xcode
      - name: Setup Xcode
        run: |
          sudo xcode-select --switch /Applications/Xcode.app
          xcodebuild -version

      # Install CocoaPods
      - name: Install CocoaPods
        run: |
          gem install cocoapods
          pod --version

      # Sync and build iOS
      - name: Sync and build iOS
        run: |
          npx cap sync ios
          cd ios/App
          pod install
          xcodebuild -workspace App.xcworkspace -scheme App -configuration Debug -sdk iphonesimulator
        env:
          IOS_VERSION: '16.0'

      # Store artifacts
      - name: Upload Android artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk

      # Note: iOS simulator build artifacts are typically not uploaded