name: Build App for Android
description: Build Capacitor app for Android

on:
    workflow_dispatch:
    pull_request:
        branches:
            - main
        types:
            - closed

jobs:
    build:
        if: github.event.workflow_dispatch || github.event.pull_request.merged == true
        runs-on: ubuntu-latest

        steps:
            # Checkout the repository
            - name: Checkout code
              uses: actions/checkout@v4

            # Setup Node.js
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "22"

            # Install dependencies
            - name: Install dependencies
              run: npm ci

            # Build the web assets
            - name: Build web assets
              run: npm run build
              env:
                  VITE_JAWG_ACCESS_TOKEN: ${{ secrets.VITE_JAWG_ACCESS_TOKEN }}
                  MODE: prod

            # Install Capacitor CLI
            - name: Install Capacitor CLI
              run: npm install -g @capacitor/cli

            # Setup Java for Android
            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                  java-version: "21"
                  distribution: "temurin"

            # Setup Android SDK
            - name: Setup Android SDK
              uses: android-actions/setup-android@v3

            # Sync and build Android
            - name: Sync and build Android
              run: |
                  npx cap sync android
                  cd android
                  ./gradlew assembleDebug
              env:
                  ANDROID_SDK_ROOT: ${{ env.ANDROID_HOME }}

            # Upload Android artifact
            - name: Upload Android artifact
              uses: actions/upload-artifact@v4
              with:
                  name: android-apk
                  path: android/app/build/outputs/apk/debug/app-debug.apk
